<a href="https://colab.research.google.com/github/shivam361v/DataScience/blob/main/ExploretoryDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns

In [5]:
df = pd.read_csv("/content/sample_data/Modified_Unicorn_Companies.csv.csv")
df['Date Joined'] = pd.to_datetime(df['Date Joined'])
df.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China..."
3,Stripe,95,2014-01-23,FinTech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG"
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita..."

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   int64
 2   Date Joined       1074 non-null   datetime64[ns]
 3   Industry          1074 non-null   object
 4   City              1057 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1074 non-null   object
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 84.0+ KB

In [7]:
df.describe()

         Valuation  Year Founded
count  1074.000000   1074.000000
mean      3.445996   2012.870577
std       8.544242      5.705494
min       1.000000   1919.000000
25%       1.000000   2011.000000
50%       2.000000   2014.000000
75%       3.000000   2016.000000
max     180.000000   2021.000000

In [8]:
df.shape

(1074, 10)

In [9]:
df['Year Joined'] = df['Date Joined'].dt.year

In [10]:
df['week'] = df['Date Joined'].dt.strftime('%Y-W%V')
df['month' ] = df['Date Joined'].dt.strftime('%Y-%m')
df['quater'] = df['Date Joined'].dt.to_period('Q').dt.strftime('%Y-Q%q')
df['year'] = df['Date Joined'].dt.strftime('%Y')

df.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,week,month,quater,year
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017,2017-W14,2017-04,2017-Q2,2017
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012,2012-W48,2012-12,2012-Q4,2012
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018,2018-W27,2018-07,2018-Q3,2018
3,Stripe,95,2014-01-23,FinTech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014,2014-W04,2014-01,2014-Q1,2014
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011,2011-W50,2011-12,2011-Q4,2011

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   int64
 2   Date Joined       1074 non-null   datetime64[ns]
 3   Industry          1074 non-null   object
 4   City              1057 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1074 non-null   object
 10  Year Joined       1074 non-null   int64
 11  week              1074 non-null   object
 12  month             1074 non-null   object
 13  quater            1074 non-null   object
 14  year              1074 non-null   object
dtypes: datetime64[ns](1), int64(3), object(11)
memory usage: 126.0+ KB

In [12]:
pd.set_option('display.max_columns', None)

Step 2 : Data Cleaning

In [13]:
df.dtypes

Company                     object
Valuation                    int64
Date Joined         datetime64[ns]
Industry                    object
City                        object
Country/Region              object
Continent                   object
Year Founded                 int64
Funding                     object
Select Investors            object
Year Joined                  int64
week                        object
month                       object
quater                      object
year                        object
dtype: object

In [15]:
df['Years To Unicorn'] = df['Date Joined'].dt.year - df['Year Founded']
df['Years To Unicorn'].describe()

count    1074.000000
mean        7.013035
std         5.331842
min        -3.000000
25%         4.000000
50%         6.000000
75%         9.000000
max        98.000000
Name: Years To Unicorn, dtype: float64

In [ ]:
df[df['Years To Unicorn'] < 0]

df[df['Years To Unicorn'] < 0]

In [18]:
df.loc[df['Company'] == 'InVision', 'Year Founded'] = 2011
df[df['Company'] == 'InVision']

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,week,month,quater,year,Years To Unicorn
527,InVision,2,2017-11-01,Internet software & services,New York,United States,North America,2011,$349M,"FirstMark Capital, Tiger Global Management, IC...",2017,2017-W44,2017-11,2017-Q4,2017,-3

In [19]:
df['Years To Unicorn'] = df['Date Joined'].dt.year - df['Year Founded']
df['Years To Unicorn'].describe()

count    1074.000000
mean        7.021415
std         5.323155
min         0.000000
25%         4.000000
50%         6.000000
75%         9.000000
max        98.000000
Name: Years To Unicorn, dtype: float64

In [20]:
df[df['Years To Unicorn'] < 0]

Empty DataFrame
Columns: [Company, Valuation, Date Joined, Industry, City, Country/Region, Continent, Year Founded, Funding, Select Investors, Year Joined, week, month, quater, year, Years To Unicorn]
Index: []