<a href="https://colab.research.google.com/github/shivam361v/DataScience/blob/main/ExploretoryDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns

In [9]:
df = pd.read_csv("/content/Modified_Unicorn_Companies.csv")
df['Date Joined'] = pd.to_datetime(df['Date Joined'])
df.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China..."
3,Stripe,95,2014-01-23,FinTech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG"
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita..."

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   int64
 2   Date Joined       1074 non-null   datetime64[ns]
 3   Industry          1074 non-null   object
 4   City              1057 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1074 non-null   object
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 84.0+ KB

In [6]:
df.describe()

         Valuation  Year Founded
count  1074.000000   1074.000000
mean      3.445996   2012.870577
std       8.544242      5.705494
min       1.000000   1919.000000
25%       1.000000   2011.000000
50%       2.000000   2014.000000
75%       3.000000   2016.000000
max     180.000000   2021.000000

In [7]:
df.shape

(1074, 11)

In [11]:
df['Year Joined'] = df['Date Joined'].dt.year

In [20]:
df['week'] = df['Date Joined'].dt.strftime('%Y-W%V')
df['month' ] = df['Date Joined'].dt.strftime('%Y-%m')
df['quater'] = df['Date Joined'].dt.to_period('Q').dt.strftime('%Y-Q%q')
df['year'] = df['Date Joined'].dt.strftime('%Y')

df.head()

,Company,Valuation,Date Joined,Industry,City,Country/Region,Continent,Year Founded,Funding,Select Investors,Year Joined,week,month,quater,year
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,$8B,"Sequoia Capital China, SIG Asia Investments, S...",2017,2017-W14,2017-04,2017-Q2,2017
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,$7B,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2012,2012-W48,2012-12,2012-Q4,2012
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,$2B,"Tiger Global Management, Sequoia Capital China...",2018,2018-W27,2018-07,2018-Q3,2018
3,Stripe,95,2014-01-23,FinTech,San Francisco,United States,North America,2010,$2B,"Khosla Ventures, LowercaseCapital, capitalG",2014,2014-W04,2014-01,2014-Q1,2014
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,$4B,"Institutional Venture Partners, Sequoia Capita...",2011,2011-W50,2011-12,2011-Q4,2011

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   int64
 2   Date Joined       1074 non-null   datetime64[ns]
 3   Industry          1074 non-null   object
 4   City              1057 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64
 8   Funding           1074 non-null   object
 9   Select Investors  1074 non-null   object
 10  Year Joined       1074 non-null   int64
 11  week              1074 non-null   object
 12  month             1074 non-null   object
 13  quater            1074 non-null   object
 14  year              1074 non-null   object
dtypes: datetime64[ns](1), int64(3), object(11)
memory usage: 126.0+ KB